In [1]:
try:
    from IPython import get_ipython
    get_ipython().magic('clear')
    get_ipython().magic('reset -f')
except:
    pass

#Importing all the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import missingno as msno
from scipy.stats import zscore as zscore
#To ignore the warnings 
import warnings as wg
wg.filterwarnings("ignore")

# Set plot style
sns.set(color_codes=True)

# Set maximum number of columns to be displayed
pd.set_option('display.max_columns', 100)


#Read the dataset file of train data
train_data=pd.read_csv("ml_case_training_data.csv")
#Read the dataset file of history data
history_data=pd.read_csv("ml_case_training_hist_data.csv")
#Read the dataset file of churn data
churn_data=pd.read_csv("ml_case_training_output.csv")

train = pd.merge(train_data, churn_data, on="id")

In [2]:
train.head()

,id,activity_new,campaign_disc_ele,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_first_activ,date_modif_prod,date_renewal,forecast_base_bill_ele,forecast_base_bill_year,forecast_bill_12m,forecast_cons,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_p1,forecast_price_energy_p2,forecast_price_pow_p1,has_gas,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,net_margin,num_years_antig,origin_up,pow_max,churn
0,48ada52261e7cf58715202705a0451c9,esoiiifxdlbkcsluxmfuacbdckommixw,NaN,lmkebamcaaclubfxadlmueccxoimlema,309275,0,10025,2012-11-07,2016-11-06,NaN,2012-11-07,2015-11-09,NaN,NaN,NaN,NaN,26520.30,10025,0.0,359.29,0.095919,0.088347,58.995952,f,831.8,-41.76,-41.76,1,1732.36,3,ldkssxwpmemidmecebumciepifcamkci,180.000,0
1,24011ae4ebbe3035111d65fa7c15bc57,NaN,NaN,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,NaN,NaN,2015-06-23,NaN,NaN,NaN,NaN,0.00,0,0.0,1.78,0.114481,0.098142,40.606701,t,0.0,25.44,25.44,2,678.99,3,lxidpiddsbxsbosboudacockeimpuepw,43.648,1
2,d29c2c54acc38ff3c0614d0a653813dd,NaN,NaN,NaN,4660,0,0,2009-08-21,2016-08-30,NaN,2009-08-21,2015-08-31,NaN,NaN,NaN,NaN,189.95,0,0.0,16.27,0.145711,0.000000,44.311378,f,0.0,16.38,16.38,1,18.89,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.800,0
3,764c75f661154dac3a6c254cd082ea7d,NaN,NaN,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,NaN,2010-04-16,2015-04-17,NaN,NaN,NaN,NaN,47.96,0,0.0,38.72,0.165794,0.087899,44.311378,f,0.0,28.60,28.60,1,6.60,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.856,0
4,bba03439a292a1e166f80264c16191cb,NaN,NaN,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,NaN,2010-03-30,2015-03-31,NaN,NaN,NaN,NaN,240.04,0,0.0,19.83,0.146694,0.000000,44.311378,f,0.0,30.22,30.22,1,25.46,6,kamkkxfxxuwbdslkwifmmcsiusiuosws,13.200,0

In [3]:
pd.DataFrame({"Data type":train.dtypes})

                         Data type
id                          object
activity_new                object
campaign_disc_ele          float64
channel_sales               object
cons_12m                     int64
cons_gas_12m                 int64
cons_last_month              int64
date_activ                  object
date_end                    object
date_first_activ            object
date_modif_prod             object
date_renewal                object
forecast_base_bill_ele     float64
forecast_base_bill_year    float64
forecast_bill_12m          float64
forecast_cons              float64
forecast_cons_12m          float64
forecast_cons_year           int64
forecast_discount_energy   float64
forecast_meter_rent_12m    float64
forecast_price_energy_p1   float64
forecast_price_energy_p2   float64
forecast_price_pow_p1      float64
has_gas                     object
imp_cons                   float64
margin_gross_pow_ele       float64
margin_net_pow_ele         float64
nb_prod_act                  int64
net_margin                 float64
num_years_antig              int64
origin_up                   object
pow_max                    float64
churn                        int64

In [4]:
pd.DataFrame({"Data type":history_data.dtypes})

             Data type
id              object
price_date      object
price_p1_var   float64
price_p2_var   float64
price_p3_var   float64
price_p1_fix   float64
price_p2_fix   float64
price_p3_fix   float64

In [5]:
train.describe()

,campaign_disc_ele,cons_12m,cons_gas_12m,cons_last_month,forecast_base_bill_ele,forecast_base_bill_year,forecast_bill_12m,forecast_cons,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_p1,forecast_price_energy_p2,forecast_price_pow_p1,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,net_margin,num_years_antig,pow_max,churn
count,0.0,1.609600e+04,1.609600e+04,1.609600e+04,3508.000000,3508.000000,3508.000000,3508.000000,16096.000000,16096.000000,15970.000000,16096.000000,15970.000000,15970.000000,15970.000000,16096.000000,16083.000000,16083.000000,16096.000000,16081.000000,16096.000000,16093.000000,16096.000000
mean,NaN,1.948044e+05,3.191164e+04,1.946154e+04,335.843857,335.843857,3837.441866,206.845165,2370.555949,1907.347229,0.991547,70.309945,0.135901,0.052951,43.533496,196.123447,22.462276,21.460318,1.347788,217.987028,5.030629,20.604131,0.099093
std,NaN,6.795151e+05,1.775885e+05,8.235676e+04,649.406000,649.406000,5425.744327,455.634288,4035.085664,5257.364759,5.160969,79.023251,0.026252,0.048617,5.212252,494.366979,23.700883,27.917349,1.459808,366.742030,1.676101,21.772421,0.298796
min,NaN,-1.252760e+05,-3.037000e+03,-9.138600e+04,-364.940000,-364.940000,-2503.480000,0.000000,-16689.260000,-85627.000000,0.000000,-242.960000,0.000000,0.000000,-0.122184,-9038.210000,-525.540000,-615.660000,1.000000,-4148.990000,1.000000,1.000000,0.000000
25%,NaN,5.906250e+03,0.000000e+00,0.000000e+00,0.000000,0.000000,1158.175000,0.000000,513.230000,0.000000,0.000000,16.230000,0.115237,0.000000,40.606701,0.000000,11.960000,11.950000,1.000000,51.970000,4.000000,12.500000,0.000000
50%,NaN,1.533250e+04,0.000000e+00,9.010000e+02,162.955000,162.955000,2187.230000,42.215000,1179.160000,378.000000,0.000000,19.440000,0.142881,0.086163,44.311378,44.465000,21.090000,20.970000,1.000000,119.680000,5.000000,13.856000,0.000000
75%,NaN,5.022150e+04,0.000000e+00,4.127000e+03,396.185000,396.185000,4246.555000,228.117500,2692.077500,1994.250000,0.000000,131.470000,0.146348,0.098837,44.311378,218.090000,29.640000,29.640000,1.000000,275.810000,6.000000,19.800000,0.000000
max,NaN,1.609711e+07,4.188440e+06,4.538720e+06,12566.080000,12566.080000,81122.630000,9682.890000,103801.930000,175375.000000,50.000000,2411.690000,0.273963,0.195975,59.444710,15042.790000,374.640000,374.640000,32.000000,24570.650000,16.000000,500.000000,1.000000

In [6]:
train["campaign_disc_ele"].isnull().values.all()

True

In [7]:
history_data.describe()

,price_p1_var,price_p2_var,price_p3_var,price_p1_fix,price_p2_fix,price_p3_fix
count,191643.000000,191643.000000,191643.000000,191643.000000,191643.000000,191643.000000
mean,0.140991,0.054412,0.030712,43.325546,10.698201,6.455436
std,0.025117,0.050033,0.036335,5.437952,12.856046,7.782279
min,0.000000,0.000000,0.000000,-0.177779,-0.097752,-0.065172
25%,0.125976,0.000000,0.000000,40.728885,0.000000,0.000000
50%,0.146033,0.085483,0.000000,44.266930,0.000000,0.000000
75%,0.151635,0.101780,0.072558,44.444710,24.339581,16.226389
max,0.280700,0.229788,0.114102,59.444710,36.490692,17.458221

In [8]:
pd.DataFrame({"Missing values (%)": train.isnull().sum()/len(train.index)*100})

                          Missing values (%)
id                                  0.000000
activity_new                       59.300447
campaign_disc_ele                 100.000000
channel_sales                      26.205268
cons_12m                            0.000000
cons_gas_12m                        0.000000
cons_last_month                     0.000000
date_activ                          0.000000
date_end                            0.012425
date_first_activ                   78.205765
date_modif_prod                     0.975398
date_renewal                        0.248509
forecast_base_bill_ele             78.205765
forecast_base_bill_year            78.205765
forecast_bill_12m                  78.205765
forecast_cons                      78.205765
forecast_cons_12m                   0.000000
forecast_cons_year                  0.000000
forecast_discount_energy            0.782803
forecast_meter_rent_12m             0.000000
forecast_price_energy_p1            0.782803
forecast_price_energy_p2            0.782803
forecast_price_pow_p1               0.782803
has_gas                             0.000000
imp_cons                            0.000000
margin_gross_pow_ele                0.080765
margin_net_pow_ele                  0.080765
nb_prod_act                         0.000000
net_margin                          0.093191
num_years_antig                     0.000000
origin_up                           0.540507
pow_max                             0.018638
churn                               0.000000

In [9]:
train.drop(['campaign_disc_ele','date_first_activ','forecast_base_bill_ele','forecast_cons','forecast_bill_12m','forecast_base_bill_year'],inplace=True,axis=1)

In [10]:
df=train.head()

In [11]:
def impute_nan(df,variable,median):
    df[variable]=df[variable].fillna(median)

median=df.net_margin.median()

median

impute_nan(df,'forecast_discount_energy',median)
impute_nan(df,'forecast_price_energy_p1',median)
impute_nan(df,'forecast_price_energy_p2',median)
impute_nan(df,'forecast_price_pow_p1',median)
impute_nan(df,'margin_gross_pow_ele',median)
impute_nan(df,'margin_net_pow_ele',median)
impute_nan(df,'net_margin',median)
impute_nan(df,'pow_max',median)

def impute_nan(df,variable):
    most_frequent_category=df[variable].mode()[0]
    df[variable].fillna(most_frequent_category,inplace=True)

for feature in ['activity_new','channel_sales','date_modif_prod']:
    impute_nan(df,feature)

df.isnull().sum()

id                          0
activity_new                0
channel_sales               0
cons_12m                    0
cons_gas_12m                0
cons_last_month             0
date_activ                  0
date_end                    0
date_modif_prod             0
date_renewal                0
forecast_cons_12m           0
forecast_cons_year          0
forecast_discount_energy    0
forecast_meter_rent_12m     0
forecast_price_energy_p1    0
forecast_price_energy_p2    0
forecast_price_pow_p1       0
has_gas                     0
imp_cons                    0
margin_gross_pow_ele        0
margin_net_pow_ele          0
nb_prod_act                 0
net_margin                  0
num_years_antig             0
origin_up                   0
pow_max                     0
churn                       0
dtype: int64

In [12]:
# fill missing values with mean column values
history_data.fillna(history_data.mean(), inplace=True)
# count the number of NaN values in each column
print(history_data.isnull().sum())

id              0
price_date      0
price_p1_var    0
price_p2_var    0
price_p3_var    0
price_p1_fix    0
price_p2_fix    0
price_p3_fix    0
dtype: int64

In [13]:
train=pd.merge(df,history_data,on='id')

In [14]:
pd.DataFrame({"Dataframe columns": train.columns})

           Dataframe columns
0                         id
1               activity_new
2              channel_sales
3                   cons_12m
4               cons_gas_12m
5            cons_last_month
6                 date_activ
7                   date_end
8            date_modif_prod
9               date_renewal
10         forecast_cons_12m
11        forecast_cons_year
12  forecast_discount_energy
13   forecast_meter_rent_12m
14  forecast_price_energy_p1
15  forecast_price_energy_p2
16     forecast_price_pow_p1
17                   has_gas
18                  imp_cons
19      margin_gross_pow_ele
20        margin_net_pow_ele
21               nb_prod_act
22                net_margin
23           num_years_antig
24                 origin_up
25                   pow_max
26                     churn
27                price_date
28              price_p1_var
29              price_p2_var
30              price_p3_var
31              price_p1_fix
32              price_p2_fix
33              price_p3_fix

In [15]:
train.dtypes

id                           object
activity_new                 object
channel_sales                object
cons_12m                      int64
cons_gas_12m                  int64
cons_last_month               int64
date_activ                   object
date_end                     object
date_modif_prod              object
date_renewal                 object
forecast_cons_12m           float64
forecast_cons_year            int64
forecast_discount_energy    float64
forecast_meter_rent_12m     float64
forecast_price_energy_p1    float64
forecast_price_energy_p2    float64
forecast_price_pow_p1       float64
has_gas                      object
imp_cons                    float64
margin_gross_pow_ele        float64
margin_net_pow_ele          float64
nb_prod_act                   int64
net_margin                  float64
num_years_antig               int64
origin_up                    object
pow_max                     float64
churn                         int64
price_date                   object
price_p1_var                float64
price_p2_var                float64
price_p3_var                float64
price_p1_fix                float64
price_p2_fix                float64
price_p3_fix                float64
dtype: object

In [16]:
train.head()

,id,activity_new,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,forecast_cons_year,forecast_discount_energy,forecast_meter_rent_12m,forecast_price_energy_p1,forecast_price_energy_p2,forecast_price_pow_p1,has_gas,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,net_margin,num_years_antig,origin_up,pow_max,churn,price_date,price_p1_var,price_p2_var,price_p3_var,price_p1_fix,price_p2_fix,price_p3_fix
0,48ada52261e7cf58715202705a0451c9,esoiiifxdlbkcsluxmfuacbdckommixw,lmkebamcaaclubfxadlmueccxoimlema,309275,0,10025,2012-11-07,2016-11-06,2012-11-07,2015-11-09,26520.3,10025,0.0,359.29,0.095919,0.088347,58.995952,f,831.8,-41.76,-41.76,1,1732.36,3,ldkssxwpmemidmecebumciepifcamkci,180.0,0,2015-01-01,0.106043,0.093474,0.067378,58.936774,36.344726,8.33426
1,48ada52261e7cf58715202705a0451c9,esoiiifxdlbkcsluxmfuacbdckommixw,lmkebamcaaclubfxadlmueccxoimlema,309275,0,10025,2012-11-07,2016-11-06,2012-11-07,2015-11-09,26520.3,10025,0.0,359.29,0.095919,0.088347,58.995952,f,831.8,-41.76,-41.76,1,1732.36,3,ldkssxwpmemidmecebumciepifcamkci,180.0,0,2015-02-01,0.106043,0.093474,0.067378,58.936774,36.344726,8.33426
2,48ada52261e7cf58715202705a0451c9,esoiiifxdlbkcsluxmfuacbdckommixw,lmkebamcaaclubfxadlmueccxoimlema,309275,0,10025,2012-11-07,2016-11-06,2012-11-07,2015-11-09,26520.3,10025,0.0,359.29,0.095919,0.088347,58.995952,f,831.8,-41.76,-41.76,1,1732.36,3,ldkssxwpmemidmecebumciepifcamkci,180.0,0,2015-03-01,0.106043,0.093474,0.067378,58.936774,36.344726,8.33426
3,48ada52261e7cf58715202705a0451c9,esoiiifxdlbkcsluxmfuacbdckommixw,lmkebamcaaclubfxadlmueccxoimlema,309275,0,10025,2012-11-07,2016-11-06,2012-11-07,2015-11-09,26520.3,10025,0.0,359.29,0.095919,0.088347,58.995952,f,831.8,-41.76,-41.76,1,1732.36,3,ldkssxwpmemidmecebumciepifcamkci,180.0,0,2015-04-01,0.106043,0.093474,0.067378,58.936774,36.344726,8.33426
4,48ada52261e7cf58715202705a0451c9,esoiiifxdlbkcsluxmfuacbdckommixw,lmkebamcaaclubfxadlmueccxoimlema,309275,0,10025,2012-11-07,2016-11-06,2012-11-07,2015-11-09,26520.3,10025,0.0,359.29,0.095919,0.088347,58.995952,f,831.8,-41.76,-41.76,1,1732.36,3,ldkssxwpmemidmecebumciepifcamkci,180.0,0,2015-05-01,0.106043,0.093474,0.067378,58.936774,36.344726,8.33426

In [17]:
def change_into_datetime(col):
    train[col]=pd.to_datetime(train[col])

In [18]:
train.columns

Index(['id', 'activity_new', 'channel_sales', 'cons_12m', 'cons_gas_12m',
       'cons_last_month', 'date_activ', 'date_end', 'date_modif_prod',
       'date_renewal', 'forecast_cons_12m', 'forecast_cons_year',
       'forecast_discount_energy', 'forecast_meter_rent_12m',
       'forecast_price_energy_p1', 'forecast_price_energy_p2',
       'forecast_price_pow_p1', 'has_gas', 'imp_cons', 'margin_gross_pow_ele',
       'margin_net_pow_ele', 'nb_prod_act', 'net_margin', 'num_years_antig',
       'origin_up', 'pow_max', 'churn', 'price_date', 'price_p1_var',
       'price_p2_var', 'price_p3_var', 'price_p1_fix', 'price_p2_fix',
       'price_p3_fix'],
      dtype='object')

In [19]:
for i in ['date_activ','date_end', 'price_date','date_renewal']:
    change_into_datetime(i)

In [20]:
train.dtypes

id                                  object
activity_new                        object
channel_sales                       object
cons_12m                             int64
cons_gas_12m                         int64
cons_last_month                      int64
date_activ                  datetime64[ns]
date_end                    datetime64[ns]
date_modif_prod                     object
date_renewal                datetime64[ns]
forecast_cons_12m                  float64
forecast_cons_year                   int64
forecast_discount_energy           float64
forecast_meter_rent_12m            float64
forecast_price_energy_p1           float64
forecast_price_energy_p2           float64
forecast_price_pow_p1              float64
has_gas                             object
imp_cons                           float64
margin_gross_pow_ele               float64
margin_net_pow_ele                 float64
nb_prod_act                          int64
net_margin                         float64
num_years_antig                      int64
origin_up                           object
pow_max                            float64
churn                                int64
price_date                  datetime64[ns]
price_p1_var                       float64
price_p2_var                       float64
price_p3_var                       float64
price_p1_fix                       float64
price_p2_fix                       float64
price_p3_fix                       float64
dtype: object

In [21]:
train['date_activ_day']=train['date_activ'].dt.day
train['date_activ_month']=train['date_activ'].dt.month
train['date_activ_year']=train['date_activ'].dt.year

In [22]:
train['date_end_day']=train['date_end'].dt.day
train['date_end_month']=train['date_end'].dt.month
train['date_end_year']=train['date_end'].dt.year

In [23]:
train['price_date_day']=train['price_date'].dt.day
train['price_date_month']=train['price_date'].dt.month
train['price_date_year']=train['price_date'].dt.year

In [24]:
train['date_renewal_day']=train['date_renewal'].dt.day
train['date_renewal_month']=train['date_renewal'].dt.month
train['date_renewal_year']=train['date_renewal'].dt.year
#train['date_modif_prod_day']=train['date_modif_prod'].dt.day
#train['date_modif_prod_month']=train['date_modif_prod'].dt.month
#train['date_modif_prod_year']=train['date_modif_prod'].dt.year

In [25]:
train.dtypes

id                                  object
activity_new                        object
channel_sales                       object
cons_12m                             int64
cons_gas_12m                         int64
cons_last_month                      int64
date_activ                  datetime64[ns]
date_end                    datetime64[ns]
date_modif_prod                     object
date_renewal                datetime64[ns]
forecast_cons_12m                  float64
forecast_cons_year                   int64
forecast_discount_energy           float64
forecast_meter_rent_12m            float64
forecast_price_energy_p1           float64
forecast_price_energy_p2           float64
forecast_price_pow_p1              float64
has_gas                             object
imp_cons                           float64
margin_gross_pow_ele               float64
margin_net_pow_ele                 float64
nb_prod_act                          int64
net_margin                         float64
num_years_antig                      int64
origin_up                           object
pow_max                            float64
churn                                int64
price_date                  datetime64[ns]
price_p1_var                       float64
price_p2_var                       float64
price_p3_var                       float64
price_p1_fix                       float64
price_p2_fix                       float64
price_p3_fix                       float64
date_activ_day                       int64
date_activ_month                     int64
date_activ_year                      int64
date_end_day                         int64
date_end_month                       int64
date_end_year                        int64
price_date_day                       int64
price_date_month                     int64
price_date_year                      int64
date_renewal_day                     int64
date_renewal_month                   int64
date_renewal_year                    int64
dtype: object

In [26]:
train.drop("activity_new",inplace=True,axis=1)
train.drop("channel_sales",inplace=True,axis=1)
train.drop("origin_up",inplace=True,axis=1)
train.drop("date_end",inplace=True,axis=1)
train.drop("date_activ",inplace=True,axis=1)
train.drop("price_date",inplace=True,axis=1)
train.drop("date_renewal",inplace=True,axis=1)
train.drop("date_modif_prod",inplace=True,axis=1)
train.drop("has_gas",inplace=True,axis=1)

In [27]:
Y = train["churn"]
X = train.drop(labels = ["id","churn"],axis = 1)

In [28]:
# Split the dataset into 75% Training set and 25% Testing set
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.25, random_state = 0)

In [29]:
!pip install xgboost

Requirement already satisfied: xgboost in c:\users\pooja\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: numpy in c:\users\pooja\anaconda3\lib\site-packages (from xgboost) (1.19.2)
Requirement already satisfied: scipy in c:\users\pooja\anaconda3\lib\site-packages (from xgboost) (1.5.2)

WARNING: You are using pip version 21.1.1; however, version 21.2.3 is available.
You should consider upgrading via the 'c:\users\pooja\anaconda3\python.exe -m pip install --upgrade pip' command.

In [39]:
#Use Random Forest Classification algorithm
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.model_selection import train_test_split 
from sklearn.model_selection import StratifiedKFold 
import xgboost as xgb
model = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
result = model.fit(X_train,Y_train)

In [40]:
def evaluate(model_, X_test_, Y_test_):
    prediction_test_ = model_.predict(X_test)
    results = pd.DataFrame({"Accuracy" : [metrics.accuracy_score(Y_test_, prediction_test_)], 
                            "Precision" : [metrics.precision_score(Y_test_, prediction_test_)], 
                            "Recall" : [metrics.recall_score(Y_test_, prediction_test_)]})
    return results

In [41]:
evaluate(model, X_test, Y_test)

   Accuracy  Precision  Recall
0       1.0        1.0     1.0